name: Kubernetes Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Kubernetes cluster
        run: kubectl get nodes

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f deployment.yaml

      - name: Apply Kubernetes Service
        run: kubectl apply -f service.yaml

      - name: Check deployment status
        run: kubectl rollout status deployment/node-app

      - name: Display Kubernetes resources
        run: |
          kubectl get deployment
          kubectl get pods
          kubectl get service
